"""Network-free unit-test suite.

The module list is intentionally explicit. New tests must be assigned to a
suite instead of being picked up implicitly by ``unittest discover``.
"""

from __future__ import annotations

import socket
import unittest
from unittest.mock import patch

from tests.suites.common import load_modules

UNIT_MODULES = (
    "api_observability",
    "api_surface",
    "app_config",
    "app_config_validation",
    "architecture_ports",
    "artifact_cli",
    "artifact_hash",
    "artifact_lifecycle",
    "artifact_prune",
    "artifact_store_pipeline_io",
    "atomic_io",
    "audio_model_cleanup",
    "audit_domain_validation",
    "audit_movie_config_path",
    "audit_render_correctness",
    "audit_tools",
    "benchmark_fixture",
    "canonical_benchmark_fixture",
    "canonical_plan_cli",
    "canonical_plan_migration",
    "canonical_plan_migration_cli",
    "canonical_plan_regeneration",
    "canonical_render_plan",
    "checked_in_workflows_schema",
    "cli_import_boundary",
    "cli_to_pipeline_fake_ports",
    "comfyui_acestep_song_generator",
    "comfyui_client",
    "comfyui_client_session",
    "comfyui_facefix_backend",
    "comfyui_facefix_h3_backend",
    "comfyui_image_backend",
    "comfyui_ingredients_video_backend",
    "comfyui_minimax_h3_backend",
    "comfyui_minimax_h3_i2v_backend",
    "comfyui_minimax_h3_r2v_backend",
    "comfyui_minimax_h3_t2v_backend",
    "comfyui_model_resolver",
    "comfyui_render_queue",
    "comfyui_seedvr2_backend",
    "comfyui_upscaler_device",
    "comfyui_video_backend_components",
    "composition_defensive",
    "concept_prompt_batcher",
    "config_examples",
    "continuation_benchmark_fixture",
    "continuation_contract",
    "continuation_contracts",
    "continuation_dependencies",
    "continuation_end_to_end",
    "continuation_render_plan",
    "continuation_scheduler",
    "continuation_segments",
    "continuity_handoff",
    "cpu_golden_contract",
    "creative_shot_payload",
    "cutless_assembly_pipeline",
    "deterministic_h3_compiler",
    "documentation_current",
    "dspy_h3_prompt_builder",
    "duration_capability",
    "effective_render_plan_projection",
    "ensemble",
    "ensemble_config",
    "ensemble_preflight",
    "errors",
    "example_project_fixture",
    "face_composite_domain",
    "face_compositor",
    "face_detection_domain",
    "face_pipeline_application",
    "face_pipeline_domain",
    "facefix_backend_selection",
    "facefix_crop_pipeline",
    "facefix_pipeline",
    "facefix_rendering",
    "failed_run_regression_fixture",
    "ffmpeg_timeout_config",
    "frozen_dataclass_immutability",
    "full_auto",
    "full_auto_cli",
    "full_auto_llm_chain",
    "full_auto_song_brief",
    "general_signatures",
    "generate_pipeline_dependencies",
    "generate_prompt_cli",
    "generate_render_plan_composition",
    "generate_render_plan_services",
    "generate_sequence_sheet",
    "global_asset_config",
    "global_asset_flow",
    "global_asset_generator",
    "global_cast_resolver",
    "global_library_cli",
    "global_library_domain",
    "gpu_benchmark",
    "h3_audio_delivery",
    "h3_guidance",
    "h3_i2v_two_pass",
    "h3_prompt_builder",
    "h3_prompt_checkpoints",
    "h3_prompt_pipeline",
    "h3_quality_profiles",
    "h3_recovery_integration",
    "h3_two_pass",
    "h3_two_pass_workflows",
    "i2v_render_plan_timeline",
    "import_boundaries",
    "ingredients_render_plan_projection",
    "ingredients_vision_prompt",
    "ingredients_workflow_files",
    "insightface_extractor",
    "job_support_composition",
    "json_artifact_store",
    "json_io",
    "legacy_workflow_overrides",
    "llm_api_key_validation",
    "llm_benchmark",
    "llm_benchmark_cli",
    "llm_boundary_classification",
    "llm_client",
    "llm_concurrency",
    "llm_parsing",
    "llm_policy",
    "llm_prompt_boundaries",
    "llm_vision_capability",
    "locked_scene_facts",
    "ltx25_audio_contract",
    "ltx25_quality_tiers",
    "ltx25_workflow_hygiene",
    "ltx_ingredients_workflow_v5",
    "ltx_msr_video_backend",
    "ltx_msr_workflow_file",
    "ltx_prompt_anchor_fixer",
    "ltx_rendering_domain",
    "ltx_video_renderer",
    "lyric_alignment",
    "media_paths",
    "media_persistence_adapter",
    "minimax_h3_frames",
    "minimax_h3_pipeline_registration",
    "minimax_h3_prompt_builder",
    "movie_continuity",
    "movie_h3_preparation",
    "movie_input_validation",
    "movie_msr_enrichment",
    "movie_pipeline_modes",
    "movie_planning_dspy_contracts",
    "movie_render_plan_log_message",
    "movie_scene_cards",
    "movie_story_plan_wiring",
    "movie_visual_local",
    "movie_workflow_audio_strip",
    "msr_enrichment_parity",
    "msr_prompt_enrichment",
    "multi_item_dspy_limits",
    "music_prepared_workflows",
    "music_video_dspy_contracts",
    "music_video_prompt_style",
    "music_video_story_plan_wiring",
    "narrative_continuity",
    "narrative_contract_derivation",
    "openshot_exporter",
    "orbitsheets_logic",
    "override_regression_corpus",
    "package_layout",
    "path_utils",
    "performance_timeline",
    "pipeline_comfyui_cache",
    "pipeline_skip_flags",
    "pipeline_utils",
    "planning_payload",
    "prepared_workflow_manifest",
    "project_asset_archive",
    "project_config",
    "project_persistence_contracts",
    "project_render_settings",
    "project_visual_consistency",
    "prompt_contract_validation",
    "prompt_generation_cast_preservation",
    "prompt_generation_references",
    "prompt_generation_service",
    "prompt_model_types",
    "prompt_pipeline",
    "prompt_relay_builder",
    "prompting_guide_loader",
    "prompting_packaging",
    "prop_interactions",
    "public_compatibility",
    "rebuild_policy",
    "rebuild_preview_application",
    "reference_bible",
    "reference_bible_tool",
    "reference_render_plan_enrichment",
    "reference_sheet_benchmark",
    "reference_sheet_planning",
    "reference_workspace_domain",
    "relay_direction_dspy_contracts",
    "relay_range",
    "render_defaults",
    "render_plan_builder",
    "render_plan_ingredients_sheets",
    "render_plan_normalizer",
    "render_plan_references",
    "render_plan_selection",
    "render_profile",
    "render_stage_selection_helpers",
    "render_storyboard_composition",
    "render_video_composition_msr",
    "render_video_composition_profiles",
    "reporting_and_stems",
    "resolution_override",
    "resource_phase",
    "resume_main_pipeline",
    "resume_plan",
    "rich_progress",
    "run_cli",
    "scene_artifact_layout",
    "scene_cast",
    "scene_duration_helpers",
    "scene_duration_limits",
    "scene_prompt_builder",
    "scene_recovery",
    "scene_reference_sheet",
    "scene_workspace_domain",
    "security_audit",
    "seedvr2_artifact_selection",
    "seedvr2_pipeline",
    "seedvr2_planner",
    "seedvr2_timeline_export",
    "semantic_intent",
    "semantic_intent_extraction",
    "semantic_intent_review",
    "semantic_intent_validation",
    "semantic_intent_wiring",
    "semantic_intent_e2e",
    "sequence_reference_pipeline",
    "sequence_to_sheet",
    "sequence_to_sheet_backend",
    "sequence_to_sheet_workflow",
    "stage_vocabulary",
    "suite_registration_guard",
    "startframe_engine",
    "story_plan",
    "story_plan_artifacts",
    "story_plan_dspy",
    "story_plan_entity_resolution",
    "storyboard_page",
    "storyboard_prompt_transformer",
    "structured_h3_builder",
    "studio_package_removed",
    "sub_step_progress",
    "subject_directive_pipeline",
    "subject_directives",
    "sync_project_render_settings",
    "timeline_transform",
    "tooling_config",
    "tools_hygiene",
    "typed_workflow_directories",
    "undeclared_dependencies",
    "url_validation",
    "video_postprocessor",
    "video_settings",
    "video_workflow_cli",
    "video_workflow_profile",
    "video_workflow_profile_config",
    "vision_references",
    "visual_consistency_application",
    "visual_consistency_domain",
    "visual_consistency_preflight",
    "vocal_assignments",
    "vocal_timeline_analyzer",
    "workflow_asset_name_replacement",
    "workflow_benchmark",
    "workflow_capability_manifest",
    "workflow_import_cli",
    "workflow_import_families",
    "workflow_import_inspector",
    "workflow_import_precedence",
    "workflow_import_render_wiring",
    "workflow_import_store",
    "workflow_inventory",
    "workflow_materializer",
    "workflow_patch_spec",
    "workflow_patcher_lora",)


def _fail_network_connection(*args: object, **kwargs: object) -> None:
    del args, kwargs
    raise AssertionError(
        "Unit tests must not open network connections; mock the LLM or HTTP client."
    )


def main() -> int:
    suite = load_modules(UNIT_MODULES)
    with patch.object(socket.socket, "connect", _fail_network_connection):
        result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
