"""Network-free unit-test suite.

The module list is intentionally explicit. New tests must be assigned to a
suite instead of being picked up implicitly by ``unittest discover``.
"""

from __future__ import annotations

import socket
import unittest
from unittest.mock import patch

from tests.suites.common import load_modules

UNIT_MODULES = (
    "api_observability",
    "api_surface",
    "app_config_validation",
    "app_config",
    "architecture_ports",
    "artifact_store_pipeline_io",
    "atomic_io",
    "audio_model_cleanup",
    "audit_domain_validation",
    "audit_movie_config_path",
    "audit_render_correctness",
    "audit_tools",
    "cli_import_boundary",
    "cli_to_pipeline_fake_ports",
    "comfyui_acestep_song_generator",
    "comfyui_client_session",
    "comfyui_client",
    "comfyui_facefix_backend",
    "comfyui_image_backend",
    "comfyui_ingredients_video_backend",
    "comfyui_minimax_h3_backend",
    "comfyui_minimax_h3_r2v_backend",
    "comfyui_minimax_h3_t2v_backend",
    "comfyui_model_resolver",
    "comfyui_seedvr2_backend",
    "comfyui_video_backend_components",
    "composition_defensive",
    "concept_prompt_batcher",
    "continuity_handoff",
    "creative_shot_payload",
    "deterministic_h3_compiler",
    "deterministic_ltx25_compiler",
    "documentation_current",
    "dspy_h3_prompt_builder",
    "duration_capability",
    "edit_audio_timeline_app",
    "errors",
    "face_composite_domain",
    "face_compositor",
    "face_detection_domain",
    "face_pipeline_application",
    "face_pipeline_domain",
    "facefix_crop_pipeline",
    "facefix_pipeline",
    "facefix_rendering",
    "frozen_dataclass_immutability",
    "full_auto_llm_chain",
    "full_auto_song_brief",
    "full_auto",
    "generate_pipeline_dependencies",
    "generate_prompt_cli",
    "generate_render_plan_composition",
    "generate_render_plan_services",
    "global_asset_config",
    "global_asset_flow",
    "global_asset_generator",
    "global_cast_resolver",
    "global_library_cli",
    "global_library_domain",
    "h3_audio_delivery",
    "h3_prompt_builder",
    "h3_prompt_checkpoints",
    "h3_prompt_pipeline",
    "h3_two_pass",
    "h3_two_pass_workflows",
    "import_boundaries",
    "ingredients_render_plan_projection",
    "ingredients_vision_prompt",
    "ingredients_workflow_files",
    "insightface_extractor",
    "insightface_tracker",
    "json_io",
    "llm_api_key_validation",
    "llm_benchmark_cli",
    "llm_benchmark",
    "llm_boundary_classification",
    "llm_client",
    "llm_concurrency",
    "llm_parsing",
    "llm_policy",
    "llm_prompt_boundaries",
    "llm_vision_capability",
    "locked_scene_facts",
    "ltx_ingredients_workflow_v5",
    "ltx_msr_video_backend",
    "ltx_msr_workflow_file",
    "ltx_prompt_anchor_fixer",
    "ltx_rendering_domain",
    "ltx_video_renderer",
    "lyric_alignment",
    "minimax_h3_frames",
    "minimax_h3_pipeline_registration",
    "minimax_h3_prompt_builder",
    "movie_h3_preparation",
    "movie_input_validation",
    "movie_msr_enrichment",
    "movie_pipeline_modes",
    "movie_planning_dspy_contracts",
    "movie_visual_local",
    "movie_workflow_audio_strip",
    "msr_prompt_enrichment",
    "multi_item_dspy_limits",
    "music_prepared_workflows",
    "music_video_dspy_contracts",
    "music_video_prompt_style",
    "openshot_exporter",
    "orbitsheets_logic",
    "package_layout",
    "path_utils",
    "pipeline_comfyui_cache",
    "pipeline_skip_flags",
    "pipeline_state_store",
    "pipeline_utils",
    "prepared_workflow_manifest",
    "project_asset_archive",
    "project_config",
    "project_reference_library",
    "project_scene_documents",
    "project_timeline_documents",
    "project_visual_consistency",
    "prompt_generation_references",
    "prompt_generation_cast_preservation",
    "prompt_generation_service",
    "prompt_model_types",
    "prompt_pipeline",
    "prompt_contract_validation",
    "prompt_relay_builder",
    "prompt_revision_application",
    "prompt_revisions",
    "prompt_seed_manager",
    "prompting_guide_loader",
    "prompting_packaging",
    "prop_interactions",
    "public_compatibility",
    "rebuild_policy",
    "rebuild_preview_application",
    "reference_bible_tool",
    "reference_bible",
    "reference_render_plan_enrichment",
    "reference_sheet_domain",
    "reference_sheet_planning",
    "reference_workspace_application",
    "reference_workspace_domain",
    "relay_direction_dspy_contracts",
    "render_plan_builder",
    "render_plan_ingredients_sheets",
    "render_plan_references",
    "render_storyboard_composition",
    "render_video_composition_msr",
    "render_video_composition_profiles",
    "resolution_override",
    "rich_progress",
    "scene_artifact_layout",
    "scene_cast",
    "scene_duration_helpers",
    "scene_duration_limits",
    "scene_prompt_builder",
    "scene_reference_sheet",
    "scene_workspace_application",
    "scene_workspace_domain",
    "security_audit",
    "seedvr2_artifact_selection",
    "seedvr2_pipeline",
    "seedvr2_planner",
    "seedvr2_timeline_export",
    "sequence_reference_pipeline",
    "sequence_to_sheet_backend",
    "sequence_to_sheet_workflow",
    "sequence_to_sheet",
    "sqlite_artifact_provenance",
    "sqlite_revision_store",
    "startframe_engine",
    "storyboard_page",
    "storyboard_prompt_transformer",
    "structured_h3_builder",
    "studio_backend",
    "studio_infra",
    "studio_jobs",
    "studio_pipeline_availability",
    "studio_rebuild_service",
    "studio_reference_workspace",
    "studio_scene_workspace",
    "sub_step_progress",
    "subject_directive_pipeline",
    "subject_directives",
    "timeline_documents_ports",
    "timeline_editing_domain",
    "timeline_impact",
    "timeline_studio_service",
    "timeline_transform",
    "tooling_config",
    "tools_imports",
    "url_validation",
    "video_postprocessor",
    "video_settings",
    "video_workflow_profile_config",
    "video_workflow_profile",
    "vision_references",
    "visual_consistency_application",
    "visual_consistency_domain",
    "visual_consistency_preflight",
    "vocal_timeline_analyzer",
    "workflow_asset_name_replacement",
    "workflow_benchmark",
    "workflow_materializer",
    "workflow_patch_spec",
)


def _fail_network_connection(*args: object, **kwargs: object) -> None:
    del args, kwargs
    raise AssertionError(
        "Unit tests must not open network connections; mock the LLM or HTTP client."
    )


def main() -> int:
    suite = load_modules(UNIT_MODULES)
    with patch.object(socket.socket, "connect", _fail_network_connection):
        result = unittest.TextTestRunner(verbosity=2).run(suite)
    return 0 if result.wasSuccessful() else 1


if __name__ == "__main__":
    raise SystemExit(main())
